### ISSUE TITLE
Allow user to create courses via frontend

### ISSUE THREAD

**Issue by WarioNeila86** [WarioNeila86/courses-fullstack-application#20]

**Comment by nickurchenko** [comment]
@WarioNeila86 hi!
sorry to bother you, but could you help me, what happened with this bug https://github.com/SeleniumHQ/docker-selenium/issues/1483?
have you found the solution? or have you created a bug on chromium or chromedriver?

**Comment by WarioNeila86** [comment]
Hi @nickurchenko, I'm afraid I can't help with this.

We decided to remove all `tap()` uses in our code and decided to use `click()` instead. Reason for this was that [TouchSequence](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/actions_exports_LegacyTouchSequence.html) was marked as deprecated in selenium-webdriver api.
